import 'package:flutter/material.dart';
import 'package:minigames/ai_games/main_menu_ai_games.dart';
import 'package:minigames/dice_roller.dart';
import 'package:minigames/risk/risk.dart';
import 'utils/authentication.dart';
import 'widgets/google_sign_in_button.dart';
import '../res/custom_colors.dart';

class MainMenuPage extends StatefulWidget {
  const MainMenuPage({super.key});

  @override
  // ignore: library_private_types_in_public_api
  _MainMenuPageState createState() => _MainMenuPageState();
}

class MenuItem {
  final IconData icon;
  final String title;
  final String subtitle;
  final Widget Function(BuildContext) function;

  MenuItem(this.icon, this.title, this.subtitle, this.function);  
}

class _MainMenuPageState extends State<MainMenuPage> {
  Widget signinButton(BuildContext context) {
    return FutureBuilder(
      future: Authentication.initializeFirebase(context: context),
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return const Text('Error initializing Firebase');
        } else if (snapshot.connectionState == ConnectionState.done) {
          return GoogleSignInButton();
        }
        return const CircularProgressIndicator(
          valueColor: AlwaysStoppedAnimation<Color>(
            CustomColors.firebaseOrange,
          ),
        );
      }
    );
  }

  @override
  Widget build(BuildContext context) {
    var widgets = <Widget>[signinButton(context)];
    final menu = <MenuItem>[
        MenuItem(Icons.gamepad, 'AI Games', 'Mini games generated by AI', 
          (context) => const AIGamesMenuPage()),
        MenuItem(Icons.map_rounded, 'Risk Dices', 'Throw dices and resolve',
          (context) => const RiskDiceSelection()),
        MenuItem(Icons.map_rounded, 'Roll Dices', 'Throw dices',
          (context) => const DiceRoller()),
        // MenuItem(Icons.map_rounded, 'Go Chess', 'Go chess game',
        //   (context) => const GoChess()),
        // MenuItem(Icons.map_rounded, 'Scrum Sizing', '',
        //   (context) => const ScrumSizingPage()),
        // MenuItem(Icons.map_rounded, 'Chess', '',
        //   (context) => const ChessBoardPage()),
        // MenuItem(Icons.map_rounded, 'Chinese Chess', '',
        //   (context) => const ChineseChessBoardPage()),
        ];

    for (var i in menu) {
      widgets.add(
          GestureDetector(
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: i.function),
              );
            },
            child: ListTile(
              leading: Icon(i.icon),
              title: Text(i.title),
              subtitle: Text(i.subtitle),
            ),
          ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('Game Menu'),
      ),
      body: ListView(
        children: widgets,
      ),
    );
  }
}